site:
  name: 'Niels Veerman'
  site: 'https://nielsveerman.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null

# Default SEO metadata
metadata:
  title:
    default: 'Niels Veerman'
    template: '%s · Niels Veerman'
  description: 'Small personal site for whatever I read or think about.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Niels Veerman'
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@nielsveerman'
    site: '@nielsveerman'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
